export const filteredCases = [
    {
        industry: [
            { name: "BI-отчеты" },
            { name: "Гос. заказ" },
            { name: "Энергетика" },
            { name: "Образование" },
            { name: "Финтех" },
            { name: "Образ жизни" },
            { name: "Медицина" },
            { name: "E-commerce" },
            { name: "Безопасность" },
            { name: "Развлечения" },
            { name: "Картография" },
        ],
    },
    {
        platforms: [
            { name: "Android" },
            { name: "Chat-system" },
            { name: "Telegram" },
            { name: "Backend" },
            { name: "Windows" },
            { name: "Панель управления" },
            { name: "Web" },
            { name: "iOS" },
        ],
    },
    {
        services: [
            { name: "Релиз" },
            { name: "Сопровождение" },
            { name: "Дизайн" },
            { name: "Тестирование" },
            { name: "Разработка" },
            { name: "Предпроектная деятельность" },
            { name: "Аналитика" },
            { name: "Приемка" },
        ],
    },
    {
        languages: [
            { name: "Node.JS" },
            { name: "Java" },
            { name: "Xamarin" },
            { name: "Wordpress" },
            { name: "Drupal 8, Angular" },
            { name: "ASP.NET Core, Azure" },
            { name: "MS Power BI" },
            { name: "1C-Битрикс" },
            { name: "Objective-C" },
            { name: "C#, UWP" },
            { name: "Python" },
            { name: "PHP" },
            { name: "Kotlin" },
            { name: "MODX" },
            { name: "Swift" },
            { name: "PhoneGap" },
            { name: "React" },
            { name: "Java, Kotlin" },
            { name: "Cordova" },
            { name: "C++" },
        ],
    },
];
